return {
  "epwalsh/pomo.nvim",
  version = "*",
  lazy = true,
  cmd = { "TimerStart", "TimerRepeat", "TimerSession" },
  dependencies = {
    "rcarriga/nvim-notify",
  },
  opts = {
    sessions = {
      pomodoro1h = {
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
      },
      pomodoro2h = {
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
      },
      pomodoro3h = {
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
      },
      pomodoro4h = {
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
        { name = "Work",        duration = "25m" },
        { name = "Short Break", duration = "5m" },
      },
    },
  }
}
